export const ONBOARDING_ERROR_MESSAGES = {
    INVALID_GOAL: "Objetivo inválido.",
    INVALID_PREFERENCE: "Preferência inválida.",
    INVALID_EXPERIENCE_LEVEL: "Nível de experiência inválido.",
    INVALID_REGION: "Região inválida.",
    INVALID_RECOMMENDED_LANGUAGE: "Linguagem recomendada inválida.",
    INVALID_RECOMMENDED_STACK: "Stack recomendada inválida.",
    ONBOARDING_NOT_FOUND: "Onboarding não encontrado.",
    ONBOARDING_ALREADY_EXISTS: "Usuário já possui onboarding.",
    ONBOARDING_ALREADY_COMPLETED: "Onboarding já foi concluído e não pode ser deletado.",
} as const;

export const ONBOARDING_ERROR_CODES = {
    INVALID_GOAL: "INVALID_GOAL",
    INVALID_PREFERENCE: "INVALID_PREFERENCE",
    INVALID_EXPERIENCE_LEVEL: "INVALID_EXPERIENCE_LEVEL",
    INVALID_REGION: "INVALID_REGION",
    INVALID_RECOMMENDED_LANGUAGE: "INVALID_RECOMMENDED_LANGUAGE",
    INVALID_RECOMMENDED_STACK: "INVALID_RECOMMENDED_STACK",
    ONBOARDING_NOT_FOUND: "ONBOARDING_NOT_FOUND",
    ONBOARDING_ALREADY_EXISTS: "ONBOARDING_ALREADY_EXISTS",
    ONBOARDING_ALREADY_COMPLETED: "ONBOARDING_ALREADY_COMPLETED",
} as const;